name: Sync Fork with Upstream Repository

on:
  schedule:
    - cron: '10 19 * * *'  # 每天 UTC 19:10 执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v3  # 更新为 v3
      with:
        persist-credentials: false

    - name: Set up Git
      run: |
        git config user.name "gameboy031"
        git config user.email "zenghaiping880@gmail.com"
        
    - name: Add upstream repository
      run: git remote add upstream https://github.com/bia-pain-bache/BPB-Worker-Panel.git
    
    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout main
        git merge upstream/main --allow-unrelated-histories  # 允许合并无关历史

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub token 认证推送
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gameboy031/BPB-Worker-Panel.git main
